### ISSUE TITLE
Lucida run time error

### ISSUE THREAD

**Issue by prakharnigam** [claritylab/lucida#122]
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/stanford/nlp/pipeline/Annotator : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at calendar.CAServiceHandler$SyncCAServiceHandler.<init>(CAServiceHandler.java:32)
    at calendar.CAServiceHandler$AsyncCAServiceHandler.<init>(CAServiceHandler.java:82)
    at calendar.CalendarDaemon.main(CalendarDaemon.java:34)
:run FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':run'.
  
  > Process 'command '/usr/lib/jvm/java-7-oracle/bin/java'' finished with non-zero exit value 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4

**Comment by yunshengb** [comment]
1. Go to `tools` and `sudo ./install_java.sh` to upgrade to java 8.

2. Come back to `lucida/calendar` and `make` again.

See if the problem still exists. Thanks!

**Comment by prakharnigam** [comment]
working, done
