### ISSUE TITLE
Memory Error: During installation

### ISSUE THREAD

**Issue by PraveenkumarDonga** [claritylab/lucida#131]
Collecting reportlab==3.0 (from -r python_requirements.txt (line 40))
  Downloading reportlab-3.0.tar.gz (1.9MB)
    100% |████████████████████████████████| 1.9MB 187kB/s 
Collecting requests==2.7.0 (from -r python_requirements.txt (line 41))
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |████████████████████████████████| 471kB 605kB/s 
Collecting scipy==0.17.1 (from -r python_requirements.txt (line 42))
  Downloading scipy-0.17.1-cp27-cp27mu-manylinux1_x86_64.whl (39.5MB)
    99% |████████████████████████████████| 39.5MB 10.4MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 810, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 649, in unpack_http_url
    hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 871, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 595, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 563, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 552, in resp_read
    decode_content=False):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 353, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 310, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError
Makefile:4: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/praveen/lucida/tools'
Makefile:18: recipe for target 'local' failed
make: *** [local] Error 2
praveen@praveen-VirtualBox:~/lucida$ 

Facing the above error during installation.
Could you please help with this ?

**Comment by yunshengb** [comment]
According to [this](https://docs.python.org/2.7/library/exceptions.html#exceptions.MemoryError), your machine probably ran out of memory. What is the RAM of your machine? Thanks!

**Comment by PraveenkumarDonga** [comment]
Hi! Yunshengb
Thank you for your Quick reply!
I found out that it is because of the RAM as you said.
Actually i am trying to install it in Ubuntu 14.04 in Vmware. Be be that  error is because of that.
I am trying to see the functionality of Lucida using Docker.
Everything got installed properly but pods are not getting started.
I attached the pic of the issue. 
Could you please help me with this.
![selection_001](https://cloud.githubusercontent.com/assets/8088246/19067494/2255be0c-8a3c-11e6-88d4-e162fb474d5b.png)

**Comment by yunshengb** [comment]
You can run `kubectl describe asrmaster-controller-965h9` to check the detailed status of your pod. My guess is that it has difficulties downloading the image or starting the pod, but please post the output here or let me know the status. Thanks a lot!

**Comment by PraveenkumarDonga** [comment]
Hi!
it is working fine. I guess it is problem with the RAM size. 
Initially I tried to run it on a system with 6GB  RAM.
Now I tried it on system with >8GB.
it is working fine now.

Thank you.
