### ISSUE TITLE
its a shame

### ISSUE THREAD

**Issue by fredhampton** [claritylab/lucida#153]
I think its a shame that the code base has not been updated and that the installs in most environments fail. 
Is anyone working on the project going to make any fixes to the code base so that it can be nearly painlessly installed ?
My understanding from reading through the issues was that there was/is a new version being developed....What is the status of this.....?

**Comment by k0105** [comment]
The "new" version that was talked about is the one you're looking at. There is currently a push to revive the project, but the availability of previous developers is a problem. While I'm not a part of ClarityLab, I have very recently tried to support this effort: I fixed Lucida to again compile on Ubuntu 14.04.5 and I've also created a mini repo to set it up via Kubernetes on 14.04.5, 16.04.1 and 16.04.2. Furthermore, you can find a generic backend to add services to Lucida in my repos. All should be integrated into this repository very soon. Until then:

https://github.com/k0105/lucida
https://github.com/k0105/mini-lucida
https://github.com/k0105/lucidagenericbackend

Best,
k0105

**Comment by fredhampton** [comment]
@k0105 Thank so much for all you are doing with the code !!!!
I m running debain on a server....What is the best way to install lucida as a web app on debian ?

Thanks !!!

**Comment by k0105** [comment]
Depends - you just want to run it? Then I would probably try the Kubernetes version first, i.e. mini-lucida. If on the other hand you want to add own components or modify existing ones, then you might want to clone lucidaserverexperiment and try to compile that. For both the chances are realistic that they run on Debian as well.

Best wishes,
k0105

**Comment by sergani** [comment]
Hello, I just wanted to pipe in and thank @k0105 for the ongoing efforts.
I'm currently trying to set up the project on an Ubuntu 14 machine.

**Comment by Gartral** [comment]
thanks for the headsup, as of now the make in /tools fails with python pip throwing a massive puke of errors `Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/serialize.py", line 55, in dumps
    "body": _b64_encode_bytes(body),
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/serialize.py", line 12, in _b64_encode_bytes
    return base64.b64encode(b).decode("ascii")
MemoryError
`

**Comment by sergani** [comment]
Hi Gartral,

Are you running a VM? If yes (and if no actually), what are the specs?

Thanks
//M


On Feb 23, 2017 8:19 PM, "Gartral" <notifications@github.com> wrote:

thanks for the headsup, as of now the make in /tools fails with python pip
throwing a massive puke of errors Traceback (most recent call last): File
"/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in
main status = self.run(options, args) File "/usr/local/lib/python2.7/
dist-packages/pip/commands/install.py", line 335, in run
wb.build(autobuilding=True) File
"/usr/local/lib/python2.7/dist-packages/pip/wheel.py",
line 749, in build self.requirement_set.prepare_files(self.finder) File
"/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in
prepare_files ignore_dependencies=self.ignore_dependencies)) File
"/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in
_prepare_file session=self.session, hashes=hashes) File
"/usr/local/lib/python2.7/dist-packages/pip/download.py", line 821, in
unpack_url hashes=hashes File "/usr/local/lib/python2.7/
dist-packages/pip/download.py", line 659, in unpack_http_url hashes) File
"/usr/local/lib/python2.7/dist-packages/pip/download.py", line 882, in
_download_http_url _download_url(resp, link, content_file, hashes) File
"/usr/local/lib/python2.7/dist-packages/pip/download.py", line 603, in
_download_url hashes.check_against_chunks(downloaded_chunks) File
"/usr/local/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in
check_against_chunks for chunk in chunks: File "/usr/local/lib/python2.7/
dist-packages/pip/download.py", line 571, in written_chunks for chunk in
chunks: File "/usr/local/lib/python2.7/dist-packages/pip/utils/ui.py", line
139, in iter for x in it: File "/usr/local/lib/python2.7/
dist-packages/pip/download.py", line 560, in resp_read
decode_content=False): File "/usr/local/lib/python2.7/
dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357,
in stream data = self.read(amt=amt, decode_content=decode_content) File
"/usr/local/lib/python2.7/dist-packages/pip/_vendor/
requests/packages/urllib3/response.py", line 314, in read data =
self._fp.read(amt) File
"/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/filewrapper.py",
line 63, in read self._close() File "/usr/local/lib/python2.7/
dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 50, in _close
self.__callback(self.__buf.getvalue()) File "/usr/local/lib/python2.7/
dist-packages/pip/_vendor/cachecontrol/controller.py", line 275, in
cache_response self.serializer.dumps(request, response, body=body), File
"/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/serialize.py",
line 55, in dumps "body": _b64_encode_bytes(body), File
"/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/serialize.py",
line 12, in _b64_encode_bytes return base64.b64encode(b).decode("ascii")
MemoryError

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/claritylab/lucida/issues/153#issuecomment-282075414>,
or mute the thread

**Comment by k0105** [comment]
Check out the fixes branch.
