### ISSUE TITLE
Issues with make in /tools

### ISSUE THREAD

**Issue by Gartral** [claritylab/lucida#156]
Ubuntu 16.04, python pip fails with 'Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/serialize.py", line 55, in dumps
    "body": _b64_encode_bytes(body),
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/serialize.py", line 12, in _b64_encode_bytes
    return base64.b64encode(b).decode("ascii")
MemoryError
'

**Comment by k0105** [comment]
Forget 16.04. I talked to the two original authors today and they clearly stated that 16.04 is currently not supported. I'm sure they'll gladly look at a solution if you want to port it, but currently Lucida is considered 14.04 only. Even 14.04 Desktop only currently, but very soon (hours to days) Server support should become available as well.

Best wishes,
k0105

**Comment by Gartral** [comment]
OK, so I've setup a VM for 14.04.5 and I'm running into a new problem that's apparently unrelated to lucida, the error follows
'
Requirement already satisfied (use --upgrade to upgrade): supervisor==3.0b2 in /usr/lib/python2.7/dist-packages (from -r python_requirements.txt (line 45))
Downloading/unpacking texttable==0.8.4 (from -r python_requirements.txt (line 46))
  Downloading texttable-0.8.4.tar.gz
  Running setup.py (path:/tmp/pip_build_root/texttable/setup.py) egg_info for package texttable
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/texttable/setup.py", line 57, in <module>
        'Topic :: Utilities',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 320, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 386, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (six 1.5.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('six>=1.6.0'))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/texttable/setup.py", line 57, in <module>

    'Topic :: Utilities',

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 320, in __init__

    _Distribution.__init__(self, attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 386, in finalize_options

    ep.require(installer=self.fetch_build_egg)

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in require

    items = working_set.resolve(reqs, env, installer, extras=self.extras)

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve

    raise VersionConflict(dist, req).with_context(dependent_req)

pkg_resources.VersionConflict: (six 1.5.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('six>=1.6.0'))

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/texttable
Storing debug log for failure in /home/lucida/.pip/pip.log
make: *** [all] Error 1
'

**Comment by gurkohli** [comment]
I've just finished set up for 16.04. There are a lot of issues that i came across while trying to compile and start and I fixed them as I went. Basically my approach was to not use the automated scripts to compile the tools but to compile them manually as it's easier to notice the errors that way. I'm adding some solutions to the errors that I came across if it helps anybody. 

P.S. - I didn't spend much time on the solutions so apologies for the clumsy writing. 
P.P.S - A minimum of 5.6 GB of RAM is used when every service is started up so make sure you have enough alloted to the VM

`MongoDB - Updated the script`
`	(https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04)`
`        For Ubuntu 16.04 LTS, follow the following after install:`
	
	`>> sudo nano /etc/systemd/system/mongodb.service
	
		[Unit]
		Description=High-performance, schema-free document-oriented database
		After=network.target

		[Service]
		User=mongodb
		ExecStart=/usr/bin/mongod --quiet --config /etc/mongod.conf

		[Install]
		WantedBy=multi-user.target
	
	>> sudo systemctl start mongodb
	>> sudo systemctl status mongodb
	>> sudo systemctl enable mongodb
	
`Error : function uses ‘auto’ type specifier without trailing return type`
`        Compile with flag "-std=c++1y"`

`Error : MoveWrapper not a member of folly`
`	MoveWrapper is moved to folly/MoveWrapper.h. Include this`

	
`Error : ZSTD stuff not found`
`	Compile with -lzstd flag`
	
`Error : Can't find hdf5.h`
`	https://github.com/NVIDIA/DIGITS/issues/156`

`Error : root_solver not a member of caffe::Caffe`
`	Remake caffe distribute "make distribute"`

`Error : Undefined reference to ZN5boost6system15system_categoryEv`
`	Make with -lboost_system`

**Comment by k0105** [comment]
Thank you, that's great. Unfortunately, I'm currently quite busy, but I'll try it early next week. If this works, it would help tremendously.
