### ISSUE TITLE
Installation problem as following http://sirius.clarity-lab.org/sirius-suite/#setup

### ISSUE THREAD

**Issue by erogol** [claritylab/lucida#22]
sudo ./compile-sirius-servers.sh raises following erroneous output

```
Sphinx4 server done.
Java Pocketsphinx server done.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
C++ Pocketsphinx server done.
***configure failed: Could not find file /include/fst/fst.h:
    you may not have installed OpenFst.  See ../tools/INSTALL ***
```

and if I run ./start-qa-server.sh, it raises also this

```
Error: Could not find or load main class info.ephyra.OpenEphyraServer
```

OpenCV installation has the following error as well

```
/home/retina18/Downloads/sirius/sirius-application/opencv-2.4.9/modules/gpu/src/nvidia/core/NCVPixelOperations.hpp(132): error: a storage class is not allowed in an explicit specialization

/home/retina18/Downloads/sirius/sirius-application/opencv-2.4.9/modules/gpu/src/nvidia/core/NCVPixelOperations.hpp(133): error: a storage class is not allowed in an explicit specialization

31 errors detected in the compilation of "/tmp/tmpxft_0000433a_00000000-21_NCVPyramid.compute_35.cpp1.ii".
CMake Error at cuda_compile_generated_NCVPyramid.cu.o.cmake:264 (message):
  Error generating file
  /home/retina18/Downloads/sirius/sirius-application/opencv-2.4.9/build/modules/gpu/CMakeFiles/cuda_compile.dir/src/nvidia/core/./cuda_compile_generated_NCVPyramid.cu.o


make[2]: *** [modules/gpu/CMakeFiles/cuda_compile.dir/src/nvidia/core/./cuda_compile_generated_NCVPyramid.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [modules/gpu/CMakeFiles/opencv_gpu.dir/all] Error 2
make: *** [all] Error 2
```

I guess something is wrong in installation scripts. 

I am on Ubuntu 14.04 with GPU support.

**Comment by jbeuckm** [comment]
I have the same issue with OpenEphyraServer
```
run-scripts$ ./start-qa-server.sh
Exception in thread "main" java.lang.NoClassDefFoundError: info/ephyra/OpenEphyraServer
```

**Comment by calibr** [comment]
I think that it can helps you to run QA server:

in `sirius-application` directory

```
$ tar xzvf question-answer.tar.gz
$ tar xzvf wiki_indri_index.tar.gz -C question-answer/
$ cd question-answer/
$ ant
```

You need apache ant for last step to build OpenEphyra.

And then run again `start-qa-server.sh`, it's seems to works fine for me:

```
./sirius-qa-test.sh "what is the speed of light"
(1) Your query text is:
what is the speed of light
(2) Sending request to server...
299,792,458 meters per second
```

**Comment by jbeuckm** [comment]
Thanks! I'm further now. When I submit a question, here is the output in the server console:

```
+++++ Analyzing question (2015-03-27 11:43:11) +++++
Normalization: what be the speed of light

Answer types:
NErate->NEspeed

Interpretations:
Property: SPEED
Target: light

Predicates:
-

+++++ Generating queries (2015-03-27 11:43:12) +++++
Query strings:
speed light
("speed of light" OR "light speed")
"light" speed light
"is the speed of light"
"the speed of light is"

+++++ Searching (2015-03-27 11:43:12) +++++
Exception in thread "Thread-24" java.lang.UnsupportedClassVersionError: lemurproject/indri/QueryEnvironment
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
Exception in thread "Thread-25" java.lang.UnsupportedClassVersionError: lemurproject/indri/QueryEnvironment
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
Exception in thread "Thread-26" java.lang.UnsupportedClassVersionError: lemurproject/indri/QueryEnvironment
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
Exception in thread "Thread-27" java.lang.UnsupportedClassVersionError: lemurproject/indri/QueryEnvironment
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
Exception in thread "Thread-28" java.lang.UnsupportedClassVersionError: lemurproject/indri/QueryEnvironment
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)


```

**Comment by erogol** [comment]
Thanks for the help. I think it should be added into documentation as well.

**Comment by saijel** [comment]
Hi @erogol,  please open a new issue if this problem still persists. Thanks!
